server:
  port: 8083

#数据源
spring:
  main:
    allow-bean-definition-overriding: true
  application:
    name: product
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/my_shop?useSSL=false&useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&allowMultiQueries=true&serverTimezone=UTC
    username: root
    password:
    driver-class-name: com.mysql.jdbc.Driver

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka/

mybatis:
  mapper-locations: classpath:/mappers/*.xml
  type-aliases-package: org.fzb.product.entity

logging:
  level:
    root: info