server:
  port: 8081

spring:
  kafka:
    bootstrap-servers:
      - localhost:9092
      - localhost:9093
      - localhost:9094
    producer:
      # transaction-id-prefix: trx-zb #设置了才可以使用事务
      acks: all
      properties:
        max:
          in:
            flight:
              requests:
                per:
                  connection: 1 # 一个connection一次发一个，结合同步发送 可以保证顺序。
        linger:
          ms: 0
          # 当生产端积累的消息达到batch-size或接收到消息linger.ms后,生产者就会将消息提交给kafka
          # linger.ms为0表示每接收到一条消息就提交给kafka,这时候batch-size其实就没用了
    consumer:
      group-id: zhenbing